const majors = [
	'Anthropology',
	'Bioengineering',
	'Bioengineering ',
	'Biological Sciences',
	'Black Diaspora and African American Studies',
	'Chemistry and Biochemistry',
	'Chinese Studies',
	'Classical Studies',
	'Cognitive Science ',
	'Communication',
	'Computer Science and Engineering',
	'Computer Science and Engineering ',
	'Critical Gender Studies',
	'Dance ',
	'Data Science',
	'Economics',
	'Education Studies',
	'Electrical and Computer Engineering',
	'Electrical and Computer Engineering ',
	'Engineering',
	'Environmental Systems Program',
	'Ethnic Studies',
	'German Studies',
	'Global Health',
	'Global South Studies',
	'Herbert Wertheim School of Public Health and Human Longevity Science',
	'History',
	'Italian Studies',
	'Japanese Studies',
	'Jewish Studies',
	'Latin American Studies',
	'Linguistics',
	'Literature',
	'Mathematics',
	'Mechanical and Aerospace Engineering',
	'Mechanical and Aerospace Engineering ',
	'Music',
	'Nano Engineering',
	'Philosophy',
	'Physics',
	'Political Science',
	'Psychology',
	'Scripps Institution of Oceanography',
	'Sociology ',
	'Structural Engineering',
	'Structural Engineering ',
	'Theatre and Dance ',
	'Urban Studies and Planning',
	'Visual Arts',
];
export default majors;
