import Head from 'next/head';

import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { getAuth } from 'firebase/auth';
import { useAuthState } from 'react-firebase-hooks/auth';

export default function Home() {
	// const app = initFirebase();
	// console.log(app);
	const auth = getAuth();
	const [user, loading] = useAuthState(auth);
	if (loading) {
		return <h1>Loading...</h1>;
	}
	return (
		<>
			<h1>{user ? user.displayName : 'Need to login'}</h1>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
		</>
	);
}
